//! PLAT-19.2 — the console's half of ordinary confirmation and governed
//! approval (decision D0, "Ordinary versus governed approval contract").
//!
//! # What the console does, and what it never does
//!
//! After an operator's Restore create is accepted, the console builds the
//! AUTHORIZATION DOCUMENT V2 for that exact object — kind, namespace, name,
//! UID, the plan hash, the requester it authenticated, the namespace's bound
//! policy name and snapshot digest, an issue time and an expiry no later than
//! the policy's `maxAgeSeconds` — and signs it with its `ConsoleConfirmation`
//! key. That signature attests ONE thing: which authenticated principal asked.
//!
//! * **Ordinary**: the signed document is the whole authorization, stored as
//!   the `Approval` the Restore references.
//! * **Governed**: the signed document is stored as a CONFIRMATION object
//!   (`<approvalRef>-confirmation`) that authorises nothing; an approver
//!   countersigns the same bytes and submits them, and only then does the
//!   referenced `Approval` exist.
//! * **Unbound** (`legacy-governed-v1`): nothing is signed. The Restore waits
//!   for today's v1 approval exactly as before.
//!
//! The controller is the final gate (D0): it re-verifies the console's
//! signature against the namespace's `TrustPolicy`, the policy digest against
//! its own copy of the same installation document, and — under Governed — the
//! approver's signature and principal. Nothing here is trusted by the
//! controller that it does not re-derive.
//!
//! # The key
//!
//! A PKCS#8 PEM file, mounted from a Secret. It is never logged, never
//! serialised, never in a response; only its key id and public half are
//! published, so an administrator can add the public half to the namespace's
//! `TrustPolicy` with usage `ConsoleConfirmation`. A `ConsoleConfirmation` key
//! can never verify evidence (D3 §7.3, `weirkeeper::verification`), so holding
//! it gives this service no evidence signing capability — which is why
//! linking the signer here is recorded in `scripts/check-one-signer.sh`
//! rather than slipped in.
//!
//! PROD-16.1: the chart's MANAGED key (`logweir-console-confirmation`) is
//! generated by the identity hook, which Helm runs AFTER this pod starts. A
//! configured key file that does not exist yet is therefore not a startup
//! refusal: it is read the first time a confirmation needs it, and until then
//! every request that would need it is refused before anything is created. A
//! file that exists and does not parse is still a refusal to start.
//!
//! # The fresh-install marker (PROD-16.1)
//!
//! An unbound namespace resolves to `confirm` on a fresh install. That fact is
//! a claim the identity hook writes, in the run that generated the identity,
//! on the installation's public identity ConfigMap
//! (`logweir.dev/approval-default`), naming the default `TrustPolicy` the same
//! run created. [`effective_policies`] reads both on every request that
//! resolves a policy and honours the claim only through
//! `weirkeeper::approval_policy::marker_verdict` — the verdict the controller
//! reaches over the same objects — so the two cannot disagree and an
//! annotation patched into an older install changes nothing. An absent
//! object, annotation or policy is unmarked: `legacy-governed-v1`.

use std::path::{Path, PathBuf};
use std::sync::OnceLock;

use chrono::{DateTime, Utc};
use logweir_core::approval_policy::{
    ApprovalMode, ApprovalPolicy, ApprovalPolicySet, AuthorizedSubject, InstallationMarker,
    PolicyRef, Requester, RestoreAuthorization, PAYLOAD_TYPE_RESTORE_AUTHORIZATION,
    RESTORE_AUTHORIZATION_FORMAT_VERSION, RESTORE_AUTHORIZATION_KIND, SUBJECT_API_VERSION,
    SUBJECT_KIND_RESTORE,
};
use logweir_evidence::keys::SigningKey;
use logweir_evidence::sign::sign_detached;
use logweir_evidence::Sidecar;

/// The suffix of a governed request's confirmation object.
pub const CONFIRMATION_SUFFIX: &str = "-confirmation";

/// The longest `approvalRef.name` whose confirmation name still fits the
/// 253-character object-name limit.
pub const MAX_GOVERNED_APPROVAL_NAME: usize = 253 - CONFIRMATION_SUFFIX.len();

/// The confirmation object's name for a governed request.
#[must_use]
pub fn confirmation_name(approval_name: &str) -> String {
    format!("{approval_name}{CONFIRMATION_SUFFIX}")
}

/// The console's `ConsoleConfirmation` signing key.
pub struct ConfirmationKey {
    key: SigningKey,
    key_id: String,
    public_pem: String,
}

impl std::fmt::Debug for ConfirmationKey {
    /// THE PRIVATE HALF IS NEVER FORMATTED. Only the key id, which is public.
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("ConfirmationKey")
            .field("key_id", &self.key_id)
            .finish_non_exhaustive()
    }
}

impl ConfirmationKey {
    /// Read a PKCS#8 PEM private key file.
    ///
    /// # Errors
    ///
    /// A reason naming the PATH, never the contents.
    pub fn from_file(path: &Path) -> Result<Self, String> {
        let key = SigningKey::from_pem_file(path).map_err(|e| {
            format!(
                "cannot read the console confirmation key {}: {e}",
                path.display()
            )
        })?;
        Self::from_key(key)
    }

    /// Wrap an in-memory key (tests, and the file loader above).
    ///
    /// # Errors
    ///
    /// When the public half cannot be rendered.
    pub fn from_key(key: SigningKey) -> Result<Self, String> {
        let public_pem = key
            .verifying_key()
            .to_public_key_pem()
            .map_err(|e| format!("cannot render the confirmation key's public half: {e}"))?;
        Ok(Self {
            key_id: key.key_id(),
            key,
            public_pem,
        })
    }

    /// The key id an administrator puts on the `TrustPolicy`.
    #[must_use]
    pub fn key_id(&self) -> &str {
        &self.key_id
    }

    /// The public half, SPKI PEM.
    #[must_use]
    pub fn public_pem(&self) -> &str {
        &self.public_pem
    }

    /// Sign exact document bytes under the v2 payload type.
    ///
    /// # Errors
    ///
    /// When the signer fails.
    pub fn sign(&self, document: &[u8]) -> Result<Sidecar, String> {
        sign_detached(&self.key, PAYLOAD_TYPE_RESTORE_AUTHORIZATION, document)
            .map_err(|e| format!("signing the authorization document: {e}"))
    }
}

/// PROD-16.1: where the installation's fresh-install marker is read — the
/// public identity ConfigMap the identity hook writes.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct InstallationIdentityRef {
    /// The release namespace.
    pub namespace: String,
    /// The public identity ConfigMap (`identity.publicConfigMapName`).
    pub config_map: String,
}

/// What this process knows about approval policy: the installation document
/// (the same bytes the controller reads) and the console's key.
#[derive(Debug, Default)]
pub struct ApprovalSettings {
    /// The installation's policies and bindings, UNMARKED: the fresh-install
    /// marker is applied per request by [`effective_policies`].
    pub policies: ApprovalPolicySet,
    /// The console's confirmation key, when it was readable at startup.
    pub confirmation: Option<ConfirmationKey>,
    /// PROD-16.1: a configured key file that did not exist at startup (the
    /// managed key, before the identity hook has run). Read on first use.
    pub pending_confirmation_file: Option<PathBuf>,
    /// The key read from [`Self::pending_confirmation_file`], once.
    pub late_confirmation: OnceLock<ConfirmationKey>,
    /// PROD-16.1: where the fresh-install marker is read; `None` is an
    /// installation whose readers never see a marker (no managed identity).
    pub installation: Option<InstallationIdentityRef>,
}

impl ApprovalSettings {
    /// Load both files and check that they fit the namespaces this console
    /// serves.
    ///
    /// # Errors
    ///
    /// A reason naming the file or the namespace.
    pub fn load(
        policy_file: Option<&Path>,
        key_file: Option<&Path>,
        namespaces: &[String],
    ) -> Result<Self, String> {
        let policies = match policy_file {
            None => ApprovalPolicySet::default(),
            Some(path) => {
                let text = std::fs::read_to_string(path).map_err(|e| {
                    format!(
                        "cannot read the approval-policy file {}: {e}",
                        path.display()
                    )
                })?;
                ApprovalPolicySet::parse(&text).map_err(|e| format!("{}: {e}", path.display()))?
            }
        };
        // PROD-16.1: a configured key file that does not exist YET is the
        // managed key before the identity hook has filled its Secret; it is
        // read on first use. A file that exists is read now, and a bad one is
        // still a refusal to start.
        let (confirmation, pending_confirmation_file) = match key_file {
            Some(path) if !path.exists() => (None, Some(path.to_path_buf())),
            Some(path) => (Some(ConfirmationKey::from_file(path)?), None),
            None => (None, None),
        };
        let settings = Self {
            policies,
            confirmation,
            pending_confirmation_file,
            ..Self::default()
        };
        settings.check(namespaces)?;
        Ok(settings)
    }

    /// The console's confirmation key, reading a pending managed key file on
    /// first use (PROD-16.1). `Ok(None)`: no key is configured, or the
    /// configured file has not been written yet.
    ///
    /// # Errors
    ///
    /// A pending file that now exists and does not parse.
    pub fn confirmation_key(&self) -> Result<Option<&ConfirmationKey>, String> {
        if let Some(key) = &self.confirmation {
            return Ok(Some(key));
        }
        if let Some(key) = self.late_confirmation.get() {
            return Ok(Some(key));
        }
        let Some(path) = &self.pending_confirmation_file else {
            return Ok(None);
        };
        if !path.exists() {
            return Ok(None);
        }
        let key = ConfirmationKey::from_file(path)?;
        tracing::info!(
            confirmation_key_id = %key.key_id(),
            "the console confirmation key the identity hook generated is now loaded"
        );
        // A concurrent first use may have set it; either value is the same file.
        let _ = self.late_confirmation.set(key);
        Ok(self.late_confirmation.get())
    }

    /// A served namespace bound to an explicit policy needs the console key:
    /// both modes carry the console's signature, and without the key every
    /// Restore there would be created and then never authorisable.
    ///
    /// A configured file that does not exist yet satisfies this: it is the
    /// managed key, which the identity hook writes after this pod starts.
    ///
    /// # Errors
    ///
    /// A reason naming the first such namespace.
    pub fn check(&self, namespaces: &[String]) -> Result<(), String> {
        if self.confirmation.is_some() || self.pending_confirmation_file.is_some() {
            return Ok(());
        }
        if let Some(namespace) = namespaces
            .iter()
            .find(|ns| !self.policies.resolve(ns).is_legacy())
        {
            return Err(format!(
                "namespace {namespace} is bound to approval policy {} and this console has no \
                 `confirmationKeyFile`: both ordinary and governed requests carry the console's \
                 ConsoleConfirmation signature (D0), so configure the key or unbind the \
                 namespace",
                self.policies.resolve(namespace).name()
            ));
        }
        Ok(())
    }
}

/// PROD-16.1: the installation's policies as THIS request sees them — the
/// document with the fresh-install marker applied.
///
/// The marker is read only when it can matter (no explicit `defaultMode`, and
/// a marker location is configured), from the public identity ConfigMap, on
/// every call: it is one small object, and a cached "unmarked" would keep a
/// fresh install strict until a restart. `NotFound` is unmarked.
///
/// # Errors
///
/// Any other failure to read the marker. A request that resolves a policy
/// must not guess: an unread marker could send a fresh install's Restore down
/// the legacy path, where nothing could ever authorise it.
pub async fn effective_policies(
    settings: &ApprovalSettings,
    kube: &crate::kube::KubeAdapter,
) -> Result<ApprovalPolicySet, crate::kube::KubeFailure> {
    let policies = settings.policies.clone();
    let Some(identity) = &settings.installation else {
        return Ok(policies);
    };
    if policies.default_mode().is_some() {
        return Ok(policies);
    }
    let document = match kube
        .get_installation_identity(&identity.namespace, &identity.config_map)
        .await
    {
        Ok(document) => document,
        Err(crate::kube::KubeFailure::NotFound) => return Ok(policies),
        Err(other) => return Err(other),
    };
    let annotation =
        document.annotation(logweir_core::approval_policy::APPROVAL_DEFAULT_ANNOTATION);
    // THE BOUND MARKER (PROD-16.1 security review): honoured only beside the
    // TrustPolicy the identity hook made in the same fresh-install run, by the
    // one verdict the controller reaches too.
    let policy = match weirkeeper::approval_policy::claimed_policy(annotation) {
        Some(name) => match kube
            .get_cluster::<weirkeeper::crds::trust_policy::TrustPolicy>(&name)
            .await
        {
            Ok(policy) => Some(policy),
            Err(crate::kube::KubeFailure::NotFound) => None,
            Err(other) => return Err(other),
        },
        None => None,
    };
    let marker = match weirkeeper::approval_policy::marker_verdict(
        annotation,
        document.data.get("key-id").map(String::as_str),
        &identity.namespace,
        policy.as_ref(),
    ) {
        Ok(marker) => marker,
        Err(refusal) => {
            tracing::warn!(
                configmap = %format!("{}/{}", identity.namespace, identity.config_map),
                refusal = refusal.as_str(),
                "a fresh-install marker is present and NOT honoured: unbound namespaces stay \
                 legacy-governed-v1"
            );
            InstallationMarker::Unmarked
        }
    };
    Ok(policies.with_installation(marker))
}

/// Whether `text` spells the words that open a private-key PEM — the console
/// page's own rule (`ui/lifecycle.js` `KEY_MARKER`: "private" then optional
/// whitespace, `_` or `-`, then "key", case-insensitive), applied again on the
/// server (review L3). D0 forbids a private key in any custom resource, and the
/// approval route stores what it is sent verbatim.
#[must_use]
pub fn carries_private_key(text: &str) -> bool {
    let lower = text.to_ascii_lowercase();
    let bytes = lower.as_bytes();
    let mut from = 0;
    while let Some(at) = lower[from..].find("private") {
        let mut i = from + at + "private".len();
        while i < bytes.len()
            && (bytes[i].is_ascii_whitespace() || bytes[i] == b'_' || bytes[i] == b'-')
        {
            i += 1;
        }
        if lower[i..].starts_with("key") {
            return true;
        }
        from = from + at + 1;
    }
    false
}

/// Build the authorization document v2 for one created Restore.
#[must_use]
#[allow(clippy::too_many_arguments)]
pub fn document(
    policy: &ApprovalPolicy,
    namespace: &str,
    name: &str,
    uid: &str,
    plan_hash: &str,
    requester: Requester,
    issued_at: DateTime<Utc>,
    ticket: Option<String>,
) -> RestoreAuthorization {
    RestoreAuthorization {
        format_version: RESTORE_AUTHORIZATION_FORMAT_VERSION.to_string(),
        kind: RESTORE_AUTHORIZATION_KIND.to_string(),
        authorization_mode: policy.mode,
        subject: AuthorizedSubject {
            api_version: SUBJECT_API_VERSION.to_string(),
            kind: SUBJECT_KIND_RESTORE.to_string(),
            namespace: namespace.to_string(),
            name: name.to_string(),
            uid: uid.to_string(),
        },
        plan_hash: plan_hash.to_string(),
        requester,
        policy: PolicyRef {
            name: policy.name.clone(),
            digest: policy.digest(),
        },
        issued_at,
        expires_at: issued_at + chrono::Duration::seconds(policy.max_age_seconds),
        ticket,
    }
}

/// Merge an approver's countersignature into the console's confirmation.
///
/// Every console signature is kept, byte for byte, and every NEW key id the
/// approver's sidecar carries is appended; a signature by a key the
/// confirmation already carries is dropped, so a sidecar can never present two
/// different signatures under one key id. The payload types must agree.
///
/// # Errors
///
/// A reason when the approver's sidecar is under another payload type or adds
/// no signature at all.
pub fn merge_countersignature(
    confirmation: &Sidecar,
    submitted: &Sidecar,
) -> Result<Sidecar, String> {
    if submitted.payload_type != PAYLOAD_TYPE_RESTORE_AUTHORIZATION
        || confirmation.payload_type != PAYLOAD_TYPE_RESTORE_AUTHORIZATION
    {
        return Err(format!(
            "the submitted sidecar is for {:?}; a governed approval countersigns an \
             authorization document v2 ({PAYLOAD_TYPE_RESTORE_AUTHORIZATION})",
            submitted.payload_type
        ));
    }
    let mut merged = confirmation.clone();
    for signature in &submitted.signatures {
        if !merged.signatures.iter().any(|s| s.keyid == signature.keyid) {
            merged.signatures.push(signature.clone());
        }
    }
    if merged.signatures.len() == confirmation.signatures.len() {
        return Err(
            "the submitted sidecar adds no signature by a key other than the console's; a \
             governed approval is a SECOND, independent signature over the same bytes"
                .to_string(),
        );
    }
    Ok(merged)
}

/// Whether `mode` needs an approver after the console's confirmation.
#[must_use]
pub const fn awaits_approver(mode: ApprovalMode) -> bool {
    matches!(mode, ApprovalMode::Governed)
}

#[cfg(test)]
mod tests {
    use super::*;

    fn policies() -> ApprovalPolicySet {
        ApprovalPolicySet::parse(
            "allowOrdinaryConfirmation: true\npolicies:\n  - name: o\n    mode: Ordinary\nnamespaces:\n  team-a: o\n",
        )
        .expect("valid")
    }

    #[test]
    fn a_bound_namespace_without_a_console_key_is_a_startup_refusal() {
        let settings = ApprovalSettings {
            policies: policies(),
            ..ApprovalSettings::default()
        };
        let err = settings
            .check(&["team-a".to_string()])
            .expect_err("refused");
        assert!(
            err.contains("team-a") && err.contains("confirmationKeyFile"),
            "{err}"
        );
        assert!(
            settings.check(&["team-b".to_string()]).is_ok(),
            "unbound is fine"
        );
    }

    #[test]
    fn the_debug_rendering_carries_no_key_material() {
        let key = ConfirmationKey::from_key(SigningKey::generate_ed25519()).expect("key");
        let text = format!("{key:?}");
        assert!(text.contains(key.key_id()));
        assert!(!text.contains("PRIVATE"), "{text}");
        assert!(key.public_pem().contains("PUBLIC KEY"));
    }

    #[test]
    fn a_document_expires_at_the_policy_maximum() {
        let set = policies();
        let binding = set.resolve("team-a");
        let policy = binding.bound().expect("bound");
        let at = Utc::now();
        let doc = document(
            policy,
            "team-a",
            "rst-1",
            "uid",
            "sha256:x",
            Requester {
                issuer: "i".into(),
                subject: "s".into(),
            },
            at,
            None,
        );
        assert_eq!(
            doc.expires_at - doc.issued_at,
            chrono::Duration::seconds(policy.max_age_seconds)
        );
        assert_eq!(doc.policy.digest, policy.digest());
        assert_eq!(doc.authorization_mode, ApprovalMode::Ordinary);
    }

    #[test]
    fn a_countersignature_is_appended_and_a_duplicate_key_is_refused() {
        let console = ConfirmationKey::from_key(SigningKey::generate_ed25519()).expect("key");
        let approver = SigningKey::generate_ed25519();
        let doc = b"{}";
        let confirmation = console.sign(doc).expect("sign");
        let mine = sign_detached(&approver, PAYLOAD_TYPE_RESTORE_AUTHORIZATION, doc).expect("sign");
        let merged = merge_countersignature(&confirmation, &mine).expect("merged");
        assert_eq!(merged.signatures.len(), 2);
        assert_eq!(merged.signatures[0].sig, confirmation.signatures[0].sig);
        assert!(merge_countersignature(&confirmation, &confirmation).is_err());
        let other_type = sign_detached(&approver, "application/other", doc).expect("sign");
        assert!(merge_countersignature(&confirmation, &other_type).is_err());
    }
}

#[cfg(test)]
mod key_material_tests {
    use super::carries_private_key;

    #[test]
    fn the_server_refuses_what_the_page_refuses() {
        for text in [
            "-----BEGIN PRIVATE KEY-----",
            "-----BEGIN EC PRIVATE KEY-----",
            "private_key",
            "Private-Key",
            "a private   key",
        ] {
            assert!(carries_private_key(text), "{text}");
        }
        for text in [
            "{\"payloadType\":\"x\",\"signatures\":[]}",
            "-----BEGIN PUBLIC KEY-----",
            "privately keyed",
            "",
        ] {
            assert!(!carries_private_key(text), "{text}");
        }
    }
}
