//! The generated OpenAPI 3.0 document.
//!
//! GENERATED FROM THE DTO TYPES, CHECKED IN, DRIFT-TESTED. The component
//! schemas come from `schemars` over `crate::contract` and `crate::problem`;
//! the path table below names every route `crate::app::router` serves. The
//! checked-in copy is `schemas/logweir-api-v1.openapi.json`, regenerated by
//! `just schema` and compared by `just schema-check` and by
//! `tests/contract.rs::the_checked_in_openapi_document_is_what_the_types_generate`.
//! Every route's possible problem codes are listed under
//! `x-logweir-problem-codes`, and a test asserts each code in
//! [`crate::problem::ProblemCode::ALL`] appears somewhere.

use schemars::gen::SchemaSettings;
use serde_json::{json, Map, Value};

use crate::contract as c;
use crate::problem::{Problem, ProblemCode};

/// The document version. `/api/v1` is not yet a stability promise.
pub const DOCUMENT_VERSION: &str = "1.0.0-alpha.1";

fn schema_ref(name: &str) -> Value {
    json!({ "$ref": format!("#/components/schemas/{name}") })
}

fn codes(list: &[ProblemCode]) -> Value {
    Value::Array(
        list.iter()
            .map(|c| Value::String(c.as_str().to_string()))
            .collect(),
    )
}

/// Problem codes any `/api/v1` route can return.
const COMMON: &[ProblemCode] = &[
    ProblemCode::HeaderNotAllowed,
    ProblemCode::MisdirectedRequest,
    ProblemCode::MethodNotAllowed,
    ProblemCode::InternalError,
    ProblemCode::Unauthenticated,
    ProblemCode::SessionExpired,
];

const NAMESPACED: &[ProblemCode] = &[ProblemCode::NamespaceForbidden, ProblemCode::Forbidden];

const KUBE: &[ProblemCode] = &[
    ProblemCode::RateLimited,
    ProblemCode::KubernetesUnavailable,
    ProblemCode::UpstreamTimeout,
];

const LIST: &[ProblemCode] = &[
    ProblemCode::MalformedRequest,
    ProblemCode::ValidationFailed,
    ProblemCode::CursorInvalid,
    ProblemCode::CursorExpired,
];

const GET: &[ProblemCode] = &[ProblemCode::MalformedRequest, ProblemCode::NotFound];

const UNSAFE: &[ProblemCode] = &[
    ProblemCode::OriginMismatch,
    ProblemCode::UnsupportedMediaType,
    ProblemCode::PayloadTooLarge,
    ProblemCode::MalformedRequest,
    ProblemCode::ValidationFailed,
];

const CREATE: &[ProblemCode] = &[
    ProblemCode::IdempotencyKeyRequired,
    ProblemCode::IdempotencyKeyInvalid,
    ProblemCode::IdempotencyConflict,
    ProblemCode::StateConflict,
];

const COMMAND: &[ProblemCode] = &[
    ProblemCode::IdempotencyKeyInvalid,
    ProblemCode::PreconditionFailed,
    ProblemCode::NotFound,
];

/// Problem codes a destination route can add.
const DESTINATION: &[ProblemCode] = &[
    ProblemCode::DestinationInvalid,
    ProblemCode::DestinationLocationImmutable,
    ProblemCode::TransportDowngradeForbidden,
];

/// Problem codes a transient-check route can add.
const CHECK: &[ProblemCode] = &[ProblemCode::RateLimited, ProblemCode::NotFound];

/// Problem codes a stored-result page can add.
const RESULT_PAGE: &[ProblemCode] = &[
    ProblemCode::ResultIntegrityFailed,
    ProblemCode::CursorInvalid,
    ProblemCode::CursorExpired,
    ProblemCode::NotFound,
];

/// Problem codes reserved for later stages, with no producing route yet.
const RESERVED: &[ProblemCode] = &[ProblemCode::ApprovalRequired, ProblemCode::PolicyMismatch];

fn all_codes(groups: &[&[ProblemCode]]) -> Vec<ProblemCode> {
    let mut out: Vec<ProblemCode> = Vec::new();
    for group in groups {
        for code in *group {
            if !out.contains(code) {
                out.push(*code);
            }
        }
    }
    out.sort_by_key(|c| c.as_str());
    out
}

struct Op<'a> {
    method: &'static str,
    operation_id: &'a str,
    summary: &'a str,
    parameters: Vec<Value>,
    request: Option<&'a str>,
    success: Vec<(&'a str, &'a str, &'a str)>,
    problems: Vec<ProblemCode>,
}

fn param(name: &str, location: &str, description: &str, schema: Value, required: bool) -> Value {
    json!({
        "name": name,
        "in": location,
        "required": required,
        "description": description,
        "schema": schema,
    })
}

fn ns() -> Value {
    param(
        "ns",
        "path",
        "An explicitly granted namespace. An ungranted namespace is namespace_forbidden whether or not it exists.",
        json!({ "type": "string" }),
        true,
    )
}

fn name() -> Value {
    param(
        "name",
        "path",
        "The object name.",
        json!({ "type": "string" }),
        true,
    )
}

fn id() -> Value {
    param(
        "id",
        "path",
        "The check's id, which is its object name.",
        json!({ "type": "string" }),
        true,
    )
}

fn list_params() -> Vec<Value> {
    vec![
        ns(),
        param(
            "limit",
            "query",
            "Page size, 1 to 200. Default 50.",
            json!({ "type": "integer", "minimum": 1, "maximum": 200, "default": 50 }),
            false,
        ),
        param(
            "cursor",
            "query",
            "The opaque nextCursor of the previous page. Bound to actor, route, namespace and filters; expires after 15 minutes.",
            json!({ "type": "string" }),
            false,
        ),
        param(
            "labelSelector",
            "query",
            "Equality-only label selector, key=value terms separated by commas.",
            json!({ "type": "string" }),
            false,
        ),
    ]
}

fn idempotency_key() -> Value {
    param(
        "Idempotency-Key",
        "header",
        "8 to 128 visible ASCII characters. The object name is derived from (actor, namespace, route, key); a replay of the same request returns 200 with the same object, a different request with the same key is idempotency_conflict.",
        json!({ "type": "string", "minLength": 8, "maxLength": 128 }),
        true,
    )
}

fn origin() -> Value {
    param(
        "Origin",
        "header",
        "Must equal the configured public origin exactly.",
        json!({ "type": "string" }),
        true,
    )
}

fn operation(op: &Op<'_>) -> Value {
    let mut responses = Map::new();
    for (status, description, schema) in &op.success {
        // An empty schema name means a response with NO body: a 204, or a 303
        // whose only payload is `Location` and `Set-Cookie`. Emitting
        // `$ref: #/components/schemas/` for those would be an invalid document.
        let response = if schema.is_empty() {
            json!({ "description": description })
        } else {
            json!({
                "description": description,
                "content": { "application/json": { "schema": schema_ref(schema) } }
            })
        };
        responses.insert((*status).to_string(), response);
    }
    responses.insert(
        "default".to_string(),
        json!({
            "description": "An application/problem+json error; the possible codes are listed in x-logweir-problem-codes.",
            "content": { "application/problem+json": { "schema": schema_ref("Problem") } }
        }),
    );
    let mut out = Map::new();
    out.insert("operationId".into(), json!(op.operation_id));
    out.insert("summary".into(), json!(op.summary));
    if !op.parameters.is_empty() {
        out.insert("parameters".into(), Value::Array(op.parameters.clone()));
    }
    if let Some(request) = op.request {
        out.insert(
            "requestBody".into(),
            json!({
                "required": true,
                "content": { "application/json": { "schema": schema_ref(request) } }
            }),
        );
    }
    out.insert("responses".into(), Value::Object(responses));
    out.insert("x-logweir-problem-codes".into(), codes(&op.problems));
    Value::Object(out)
}

fn paths() -> Value {
    let list = |id: &'static str, summary: &'static str, schema: &'static str| Op {
        method: "get",
        operation_id: id,
        summary,
        parameters: list_params(),
        request: None,
        success: vec![("200", "One page.", schema)],
        problems: all_codes(&[COMMON, NAMESPACED, KUBE, LIST]),
    };
    let get_one = |id: &'static str, summary: &'static str, schema: &'static str| Op {
        method: "get",
        operation_id: id,
        summary,
        parameters: vec![ns(), name()],
        request: None,
        success: vec![("200", "The object.", schema)],
        problems: all_codes(&[COMMON, NAMESPACED, KUBE, GET]),
    };
    let create =
        |id: &'static str, summary: &'static str, request: &'static str, schema: &'static str| Op {
            method: "post",
            operation_id: id,
            summary,
            parameters: vec![ns(), idempotency_key(), origin()],
            request: Some(request),
            success: vec![
                ("201", "Created.", schema),
                (
                    "200",
                    "Replayed an identical earlier request; the same object.",
                    schema,
                ),
            ],
            problems: all_codes(&[COMMON, NAMESPACED, KUBE, UNSAFE, CREATE]),
        };

    let table: Vec<(&str, Vec<Op<'_>>)> = vec![
        (
            "/healthz",
            vec![Op {
                method: "get",
                operation_id: "getHealthz",
                summary: "Process liveness.",
                parameters: vec![],
                request: None,
                success: vec![("200", "Alive.", "HealthStatus")],
                problems: all_codes(&[&[ProblemCode::HeaderNotAllowed, ProblemCode::MisdirectedRequest]]),
            }],
        ),
        (
            "/readyz",
            vec![Op {
                method: "get",
                operation_id: "getReadyz",
                summary: "Readiness: configuration valid and Kubernetes reachable. No detail is returned.",
                parameters: vec![],
                request: None,
                success: vec![("200", "Ready.", "HealthStatus")],
                problems: all_codes(&[&[
                    ProblemCode::HeaderNotAllowed,
                    ProblemCode::MisdirectedRequest,
                    ProblemCode::KubernetesUnavailable,
                ]]),
            }],
        ),
        (
            "/api/v1/session",
            vec![Op {
                method: "get",
                operation_id: "getSession",
                summary: "The actor, its roles and explicit namespace grants, the synchronizer CSRF token and the capability flags. In shared mode the CSRF token must be sent in X-CSRF-Token on every unsafe method.",
                parameters: vec![],
                request: None,
                success: vec![("200", "The session.", "SessionResponse")],
                problems: all_codes(&[COMMON]),
            }],
        ),
        (
            "/api/v1/session/logout",
            vec![Op {
                method: "post",
                operation_id: "logout",
                summary: "Clear the session cookie. Shared mode only; it is an unsafe method, so it requires the exact Origin, application/json and the synchronizer token like every other mutation.",
                parameters: vec![origin()],
                request: None,
                success: vec![("204", "The session cookie is cleared.", "")],
                problems: all_codes(&[COMMON, &[ProblemCode::OriginMismatch, ProblemCode::UnsupportedMediaType, ProblemCode::NotFound]]),
            }],
        ),
        (
            "/auth/login",
            vec![Op {
                method: "get",
                operation_id: "authLogin",
                summary: "Begin an OpenID Connect Authorization Code + PKCE S256 sign-in. Shared mode only; answers 303 to the provider's authorization endpoint and sets the short-lived __Host-logweir_login cookie holding state, nonce and the PKCE verifier.",
                parameters: vec![param(
                    "next",
                    "query",
                    "Where to land after signing in. Only a path under /ui/ on this origin; anything else is ignored.",
                    json!({ "type": "string" }),
                    false,
                )],
                request: None,
                success: vec![("303", "Redirect to the identity provider.", "")],
                problems: all_codes(&[&[
                    ProblemCode::HeaderNotAllowed,
                    ProblemCode::MisdirectedRequest,
                    ProblemCode::NotFound,
                    ProblemCode::RateLimited,
                    ProblemCode::KubernetesUnavailable,
                ]]),
            }],
        ),
        (
            "/auth/callback",
            vec![Op {
                method: "get",
                operation_id: "authCallback",
                summary: "Finish a sign-in. Shared mode only; validates state, exchanges the code with PKCE, validates the ID token (exact issuer, audience, allowed algorithm, JWKS signature, exp, iat, nonce) and sets __Host-logweir_session. The browser never receives a provider token.",
                parameters: vec![
                    param("code", "query", "The authorization code.", json!({ "type": "string" }), false),
                    param("state", "query", "The state this service issued.", json!({ "type": "string" }), false),
                ],
                request: None,
                success: vec![("303", "Redirect to the console.", "")],
                problems: all_codes(&[&[
                    ProblemCode::HeaderNotAllowed,
                    ProblemCode::MisdirectedRequest,
                    ProblemCode::NotFound,
                    ProblemCode::RateLimited,
                    ProblemCode::Unauthenticated,
                ]]),
            }],
        ),
        (
            "/api/v1/namespaces",
            vec![Op {
                method: "get",
                operation_id: "listNamespaces",
                summary: "The configured namespace grants. Core Namespace objects are never listed.",
                parameters: vec![],
                request: None,
                success: vec![("200", "The grants.", "NamespaceListResponse")],
                problems: all_codes(&[COMMON]),
            }],
        ),
        (
            "/api/v1/namespaces/{ns}/connections",
            vec![
                list("listConnections", "KafkaCluster projections. Secret reference names only.", "ConnectionList"),
                create(
                    "createConnection",
                    "Create a KafkaCluster that references an existing credential Secret by name.",
                    "CreateConnectionRequest",
                    "ConnectionResponse",
                ),
            ],
        ),
        (
            "/api/v1/namespaces/{ns}/connections/{name}",
            vec![get_one("getConnection", "One KafkaCluster projection.", "ConnectionResponse")],
        ),
        (
            "/api/v1/cadence-previews",
            vec![Op {
                method: "get",
                operation_id: "previewCadence",
                summary: "What a cron expression, or a preset, will actually do in a time zone: the next runs as UTC instants with their local wall times and DST markers. Computed by the same module the scheduler uses; the browser never evaluates cron. It reads nothing from Kubernetes and takes no namespace, so it needs permission to read schedules in at least one granted namespace.",
                parameters: vec![
                    param("schedule", "query", "A five-field cron expression or @hourly/@daily/@weekly. Exactly one of schedule or preset.", json!({ "type": "string", "maxLength": 128 }), false),
                    param("preset", "query", "hourly, everyNHours, daily, weekly or monthly, with that preset's parameters. The response carries the canonical expression it compiled to.", json!({ "type": "string", "enum": ["hourly", "everyNHours", "daily", "weekly", "monthly"] }), false),
                    param("minute", "query", "0 to 59. A parameter of every preset.", json!({ "type": "integer", "minimum": 0, "maximum": 59 }), false),
                    param("hour", "query", "0 to 23. daily, weekly and monthly.", json!({ "type": "integer", "minimum": 0, "maximum": 23 }), false),
                    param("dayOfWeek", "query", "0 to 6, 0 = Sunday. weekly only.", json!({ "type": "integer", "minimum": 0, "maximum": 6 }), false),
                    param("dayOfMonth", "query", "1 to 28. monthly only; 29 to 31 are not a monthly cadence.", json!({ "type": "integer", "minimum": 1, "maximum": 28 }), false),
                    param("n", "query", "2, 3, 4, 6, 8 or 12. everyNHours only: */n matches local wall-clock hours divisible by n, not n hours after creation.", json!({ "type": "integer", "enum": [2, 3, 4, 6, 8, 12] }), false),
                    param("timeZone", "query", "An IANA zone name. Absent means UTC and reproduces the pre-PLAT-04.2 slots exactly.", json!({ "type": "string", "maxLength": 64 }), false),
                    param("count", "query", "1 to 20. Default 10. A shorter answer is real: an expression can run out of firings.", json!({ "type": "integer", "minimum": 1, "maximum": 20, "default": 10 }), false),
                    param("after", "query", "An RFC 3339 instant to walk strictly after. Default: the server's now.", json!({ "type": "string", "format": "date-time" }), false),
                ],
                request: None,
                success: vec![("200", "The canonical expression, the effective zone, the tz database that resolved it, and the firings.", "CadencePreviewResponse")],
                problems: all_codes(&[COMMON, &[ProblemCode::Forbidden, ProblemCode::MalformedRequest, ProblemCode::ValidationFailed]]),
            }],
        ),
        (
            "/api/v1/namespaces/{ns}/schedules",
            vec![
                list("listSchedules", "BackupSchedule projections.", "ScheduleList"),
                create("createSchedule", "Create a BackupSchedule.", "CreateScheduleRequest", "ScheduleResponse"),
            ],
        ),
        (
            "/api/v1/namespaces/{ns}/schedules/{name}",
            vec![
                get_one("getSchedule", "One BackupSchedule projection.", "ScheduleResponse"),
                Op {
                    method: "put",
                    operation_id: "updateSchedulePolicy",
                    summary: "Replace a schedule's FUTURE policy under expectedGeneration. The whole policy is sent and a field omitted is removed. spec.sourceRef is not on the request: a different cluster is a different schedule, and naming it is 422 sourceRef: field_immutable. It never touches a Backup that already exists, its frozen inputs or its Job. Idempotency-Key is refused: the precondition is the idempotence.",
                    parameters: vec![ns(), name(), origin()],
                    request: Some("UpdateSchedulePolicyRequest"),
                    success: vec![("200", "The edited schedule, with its new generation.", "ScheduleResponse")],
                    problems: all_codes(&[COMMON, NAMESPACED, KUBE, UNSAFE, COMMAND]),
                },
            ],
        ),
        (
            "/api/v1/namespaces/{ns}/schedules/{name}:set-suspension",
            vec![Op {
                method: "post",
                operation_id: "setScheduleSuspension",
                summary: "Set spec.suspend, the schedule's one mutable field, if expectedResourceVersion is current. Idempotency-Key is refused.",
                parameters: vec![ns(), name(), origin()],
                request: Some("SetSuspensionRequest"),
                success: vec![("200", "The updated schedule.", "ScheduleResponse")],
                problems: all_codes(&[COMMON, NAMESPACED, KUBE, UNSAFE, COMMAND]),
            }],
        ),
        (
            "/api/v1/namespaces/{ns}/backups",
            vec![
                list("listBackups", "Backup projections with a status summary.", "BackupList"),
                Op {
                    method: "post",
                    operation_id: "createBackup",
                    summary: "Back up now. With scheduleRef the schedule's current revision is copied and recorded (uid, generation, runPolicySha256) and a policy field beside it is 422; without it the body is the policy, for a cluster with no schedule yet. A suspended schedule, an invalid cadence, an active Forbid run and a schedule deleted a second later none of them block the run. Readiness is recorded, never obeyed.",
                    parameters: vec![ns(), idempotency_key(), origin()],
                    request: Some("CreateBackupRequest"),
                    success: vec![
                        ("201", "Created; the run and the schedule it came from.", "ManualBackupResponse"),
                        ("200", "Replayed an identical earlier request; the same run and the same UID.", "ManualBackupResponse"),
                    ],
                    problems: all_codes(&[COMMON, NAMESPACED, KUBE, UNSAFE, CREATE, &[ProblemCode::PolicyChanged, ProblemCode::NotFound]]),
                },
            ],
        ),
        (
            "/api/v1/namespaces/{ns}/backups/{name}",
            vec![get_one("getBackup", "One Backup projection.", "BackupResponse")],
        ),
        (
            "/api/v1/namespaces/{ns}/restores",
            vec![
                list("listRestores", "Restore projections with a status summary; planBytes omitted.", "RestoreList"),
                create(
                    "createRestore",
                    "Create a Restore. planBytes is opaque, checked against planHash and stored unchanged.",
                    "CreateRestoreRequest",
                    "RestoreResponse",
                ),
            ],
        ),
        (
            "/api/v1/namespaces/{ns}/restores/{name}",
            vec![get_one("getRestore", "One Restore projection, planBytes included.", "RestoreResponse")],
        ),
        (
            "/api/v1/namespaces/{ns}/approvals",
            vec![list("listApprovals", "Approval metadata; no documents.", "ApprovalList")],
        ),
        (
            "/api/v1/namespaces/{ns}/approvals/{name}",
            vec![get_one("getApproval", "One Approval's metadata; no documents.", "ApprovalResponse")],
        ),
        (
            "/api/v1/namespaces/{ns}/approvals/{name}/packet",
            vec![get_one(
                "getApprovalPacket",
                "The approval and sidecar documents, verbatim.",
                "ApprovalPacketResponse",
            )],
        ),
        (
            "/api/v1/namespaces/{ns}/destinations",
            vec![
                list(
                    "listDestinations",
                    "Saved destinations. Credential REFERENCES only: a Secret name and the key names inside it, never a value.",
                    "DestinationList",
                ),
                Op {
                    method: "post",
                    operation_id: "createDestination",
                    summary: "Create a BackupDestination. The object's name is the `name` field, because every schedule, backup and restore references a destination by name. A grant may carry a credential VALUE once in access.*.secret.new; it becomes a Secret owned by the destination and is never read back or echoed.",
                    parameters: vec![ns(), idempotency_key(), origin()],
                    request: Some("CreateDestinationRequest"),
                    success: vec![
                        ("201", "Created.", "DestinationResponse"),
                        ("200", "Replayed an identical earlier request; the same object.", "DestinationResponse"),
                    ],
                    problems: all_codes(&[COMMON, NAMESPACED, KUBE, UNSAFE, CREATE, DESTINATION]),
                },
            ],
        ),
        (
            "/api/v1/namespaces/{ns}/destinations:from-legacy",
            vec![Op {
                method: "post",
                operation_id: "createDestinationFromLegacy",
                summary: "Adopt the location of a legacy BackupSchedule or Backup as a BackupDestination. THIS BUILD ALWAYS REFUSES with legacy_location_unknown: a legacy archive.url carries the bucket and the prefix and nothing else, and the two sources that record the endpoint, region, addressing and transport — the frozen execution inputs of a succeeded Backup and the installation policy ConfigMap — are not readable here. Guessing them would move the location, and locationDigest is computed over exactly those fields. Create the destination explicitly until W11 lands. Existing objects are never mutated.",
                parameters: vec![ns(), idempotency_key(), origin()],
                request: Some("DestinationFromLegacyRequest"),
                success: vec![
                    ("201", "Created. No source this build can read produces one yet; see the summary.", "DestinationResponse"),
                    ("200", "Replayed an identical earlier request.", "DestinationResponse"),
                ],
                problems: all_codes(&[COMMON, NAMESPACED, KUBE, UNSAFE, CREATE, DESTINATION, &[ProblemCode::LegacyLocationUnknown, ProblemCode::LegacyLocationMismatch, ProblemCode::NotFound]]),
            }],
        ),
        (
            "/api/v1/namespaces/{ns}/destinations/{name}",
            vec![get_one("getDestination", "One destination, with the last explicit access test.", "DestinationResponse")],
        ),
        (
            "/api/v1/namespaces/{ns}/destinations/{name}:update-access",
            vec![Op {
                method: "post",
                operation_id: "updateDestinationAccess",
                summary: "Rotate the four grants and the CA reference under an expectedGeneration precondition. It cannot name the location or the transport, and it refuses Idempotency-Key. A grant carrying a credential VALUE whose deterministic Secret already exists is state_conflict: this service holds `create` on Secrets and nothing else, so the value was NOT written and nothing was changed.",
                parameters: vec![ns(), name(), origin()],
                request: Some("UpdateDestinationAccessRequest"),
                success: vec![("200", "The rotated destination.", "DestinationResponse")],
                problems: all_codes(&[COMMON, NAMESPACED, KUBE, UNSAFE, COMMAND, DESTINATION, &[ProblemCode::StateConflict]]),
            }],
        ),
        (
            "/api/v1/namespaces/{ns}/destinations/{name}:test",
            vec![Op {
                method: "post",
                operation_id: "testDestination",
                summary: "Start a DestinationAccess Preflight for this destination and answer 202 with it. Absent roles means every role the destination configures.",
                parameters: vec![ns(), name(), idempotency_key(), origin()],
                request: Some("TestDestinationRequest"),
                success: vec![
                    ("202", "The started test.", "PreflightResponse"),
                    ("200", "Replayed an identical earlier request.", "PreflightResponse"),
                ],
                problems: all_codes(&[COMMON, NAMESPACED, KUBE, UNSAFE, CREATE, CHECK]),
            }],
        ),
        (
            "/api/v1/namespaces/{ns}/destinations/{name}/usage",
            vec![Op {
                method: "get",
                operation_id: "getDestinationUsage",
                summary: "Schedules and backups labelled for this destination, bounded to 100 each. `basis` states how the lists were built, so an empty answer is not read as \"nothing uses this\".",
                parameters: vec![ns(), name()],
                request: None,
                success: vec![("200", "The bounded usage.", "DestinationUsageResponse")],
                problems: all_codes(&[COMMON, NAMESPACED, KUBE, GET]),
            }],
        ),
        (
            "/api/v1/namespaces/{ns}/connections/{name}/topic-discoveries",
            vec![
                Op {
                    method: "get",
                    operation_id: "listConnectionTopicDiscoveries",
                    summary: "Discoveries for one connection. With latest=true it answers the two slots instead of a page: a failed attempt never hides the last successful inventory, and a successful inventory never hides that the newest attempt failed.",
                    parameters: {
                        let mut p = list_params();
                        p.insert(1, name());
                        p.push(param("latest", "query", "true returns {latestAttempt, lastSuccessful} instead of a page.", json!({ "type": "boolean" }), false));
                        p
                    },
                    request: None,
                    success: vec![
                        ("200", "One page, or the two slots with latest=true.", "TopicDiscoveryList"),
                    ],
                    problems: all_codes(&[COMMON, NAMESPACED, KUBE, LIST, GET]),
                },
                Op {
                    method: "post",
                    operation_id: "createTopicDiscovery",
                    summary: "Start a bounded topic inventory. 202 with the new check, or 200 with reused=true when a fresh succeeded discovery with the same parameters and connection binding exists and reuseFresh is set. Rate limited per actor and namespace.",
                    parameters: vec![ns(), name(), idempotency_key(), origin()],
                    request: Some("CreateTopicDiscoveryRequest"),
                    success: vec![
                        ("202", "Accepted; the check has been created.", "TopicDiscoveryResponse"),
                        ("200", "A replay, or a reused fresh result.", "TopicDiscoveryResponse"),
                    ],
                    problems: all_codes(&[COMMON, NAMESPACED, KUBE, UNSAFE, CREATE, CHECK]),
                },
            ],
        ),
        (
            "/api/v1/namespaces/{ns}/topic-discoveries/{id}",
            vec![
                Op {
                    method: "get",
                    operation_id: "getTopicDiscovery",
                    summary: "One discovery. `visibility` is never better than unknown without an explicit attestation: a successful Kafka list alone says nothing about whether it was whole. `stale` is recomputed per read against the connection as it is now.",
                    parameters: vec![ns(), id()],
                    request: None,
                    success: vec![("200", "The discovery.", "TopicDiscoveryResponse")],
                    problems: all_codes(&[COMMON, NAMESPACED, KUBE, GET]),
                },
            ],
        ),
        (
            "/api/v1/namespaces/{ns}/topic-discoveries/{id}:cancel",
            vec![Op {
                method: "post",
                operation_id: "cancelTopicDiscovery",
                summary: "Ask an unfinished discovery to stop. Idempotent: repeating it is 200, and cancelling a finished check is 200 with alreadyTerminal. An operator may cancel only the checks it started; an administrator of the namespace may cancel any. Nothing is deleted. Idempotency-Key is refused.",
                parameters: vec![ns(), id(), origin()],
                request: None,
                success: vec![("200", "The state after the request.", "CancelResponse")],
                problems: all_codes(&[COMMON, NAMESPACED, KUBE, UNSAFE, COMMAND, &[ProblemCode::StateConflict]]),
            }],
        ),
        (
            "/api/v1/namespaces/{ns}/topic-discoveries/{id}/topics",
            vec![Op {
                method: "get",
                operation_id: "listDiscoveredTopics",
                summary: "One page of a stored inventory, read from the immutable result chunks the controller committed. Each chunk is verified by owner UID, immutability and digest before a row is served. At most eight chunks are read per request: a sparse q returns a short page with scan.complete=false and a cursor.",
                parameters: vec![
                    ns(),
                    id(),
                    param("limit", "query", "Page size, 1 to 200. Default 50.", json!({ "type": "integer", "minimum": 1, "maximum": 200, "default": 50 }), false),
                    param("cursor", "query", "The opaque nextCursor of the previous page, bound to the actor, the discovery UID, the inventory digest and the filters.", json!({ "type": "string" }), false),
                    param("q", "query", "Case-insensitive substring of the topic name.", json!({ "type": "string" }), false),
                    param("prefix", "query", "Name prefix. Whole chunks outside it are skipped without being read.", json!({ "type": "string" }), false),
                    param("internal", "query", "include or exclude (default). Only meaningful when internal topics were stored.", json!({ "type": "string", "enum": ["include", "exclude"] }), false),
                    param("errored", "query", "include (default), exclude or only.", json!({ "type": "string", "enum": ["include", "exclude", "only"] }), false),
                ],
                request: None,
                success: vec![("200", "One page, in stored (bytewise name) order.", "TopicPageResponse")],
                problems: all_codes(&[COMMON, NAMESPACED, KUBE, LIST, RESULT_PAGE]),
            }],
        ),
        (
            "/api/v1/namespaces/{ns}/preflights",
            vec![Op {
                method: "post",
                operation_id: "createPreflight",
                summary: "Start a readiness check for a Backup, a Restore or a destination's grants. planBytes is opaque: planHash is checked against the SHA-256 of exactly those bytes and they are stored unchanged. The verdict is advisory and every execution-time guard still runs.",
                parameters: vec![ns(), idempotency_key(), origin()],
                request: Some("CreatePreflightRequest"),
                success: vec![
                    ("202", "Accepted; the check has been created.", "PreflightResponse"),
                    ("200", "Replayed an identical earlier request.", "PreflightResponse"),
                ],
                problems: all_codes(&[COMMON, NAMESPACED, KUBE, UNSAFE, CREATE, CHECK]),
            }],
        ),
        (
            "/api/v1/namespaces/{ns}/preflights/{id}",
            vec![
                Op {
                    method: "get",
                    operation_id: "getPreflight",
                    summary: "One readiness result. `applicable` and `stale` are recomputed on every read against the planHash the caller sends, so an edited plan, a replaced referent or an expired result is never rendered as current readiness. An actor bound only as Approver reads Restore results and nothing else.",
                    parameters: vec![
                        ns(),
                        id(),
                        param("planHash", "query", "sha256:<64 lowercase hex> of the plan the caller is looking at now. A result bound to a different hash is stale.", json!({ "type": "string" }), false),
                    ],
                    request: None,
                    success: vec![("200", "The result.", "PreflightResponse")],
                    problems: all_codes(&[COMMON, NAMESPACED, KUBE, GET, &[ProblemCode::ValidationFailed]]),
                },
            ],
        ),
        (
            "/api/v1/namespaces/{ns}/preflights/{id}:cancel",
            vec![Op {
                method: "post",
                operation_id: "cancelPreflight",
                summary: "Ask an unfinished preflight to stop. Same rules as a discovery cancel.",
                parameters: vec![ns(), id(), origin()],
                request: None,
                success: vec![("200", "The state after the request.", "CancelResponse")],
                problems: all_codes(&[COMMON, NAMESPACED, KUBE, UNSAFE, COMMAND, &[ProblemCode::StateConflict]]),
            }],
        ),
        (
            "/api/v1/namespaces/{ns}/preflights/{id}/details",
            vec![Op {
                method: "get",
                operation_id: "listPreflightDetails",
                summary: "One page of a preflight's detail document, verified by owner UID, immutability and digest before a row is served.",
                parameters: vec![
                    ns(),
                    id(),
                    param("check", "query", "Only entries the producer attributed to this check id.", json!({ "type": "string" }), false),
                    param("limit", "query", "Page size, 1 to 200. Default 50.", json!({ "type": "integer", "minimum": 1, "maximum": 200, "default": 50 }), false),
                    param("cursor", "query", "The opaque nextCursor of the previous page.", json!({ "type": "string" }), false),
                ],
                request: None,
                success: vec![("200", "One page, in stored order.", "DetailPageResponse")],
                problems: all_codes(&[COMMON, NAMESPACED, KUBE, LIST, RESULT_PAGE]),
            }],
        ),
        (
            "/api/v1/namespaces/{ns}/operations/{kind}/{name}",
            vec![Op {
                method: "get",
                operation_id: "getOperation",
                summary: "The normalized status of one Backup, Restore, TopicDiscovery or Preflight. For a backup or a restore the body is an OperationResponse: result and evidence verification are separate, and NotAttempted is never verified success. For a discovery or a preflight it is a CheckOperationResponse, which carries none of those fields because a transient check has none of those facts.",
                parameters: vec![
                    ns(),
                    param(
                        "kind",
                        "path",
                        "backup, restore, discovery or preflight.",
                        json!({ "type": "string", "enum": ["backup", "restore", "discovery", "preflight"] }),
                        true,
                    ),
                    name(),
                ],
                request: None,
                success: vec![
                    ("200", "The normalized durable run (backup, restore), or the normalized transient check (discovery, preflight) — two shapes, because a check has no archive result, no signed evidence and no verification verdict.", "OperationViewResponse"),
                ],
                problems: all_codes(&[COMMON, NAMESPACED, KUBE, GET]),
            }],
        ),
        (
            "/api/v1/namespaces/{ns}/operations/{kind}/{name}/events",
            vec![Op {
                method: "get",
                operation_id: "streamOperationEvents",
                summary: "A bounded text/event-stream of one backup's or restore's normalized status. Event types are operation, reset, heartbeat and end; the event id is the object's resourceVersion and Last-Event-ID resumes with a reset snapshot when it is not the version the stream opened at. Every bound is the server's: the connection is closed after 300 s, a heartbeat is sent every 15 s of silence, and concurrent streams per principal per namespace are capped. NO query parameter is accepted, so no token can be placed in the URL; the stream is authenticated by the same session cookie as every other route and authorized once, at subscribe, for operation.read and operation.stream.",
                parameters: vec![
                    ns(),
                    param(
                        "kind",
                        "path",
                        "backup or restore. A transient check has a read route and no stream.",
                        json!({ "type": "string", "enum": ["backup", "restore"] }),
                        true,
                    ),
                    name(),
                    param(
                        "Last-Event-ID",
                        "header",
                        "The resourceVersion of the last event received. Decimal digits, at most 64 of them; anything else is malformed_request.",
                        json!({ "type": "string" }),
                        false,
                    ),
                ],
                request: None,
                success: vec![("200", "The event stream. text/event-stream, not application/json.", "")],
                problems: all_codes(&[COMMON, NAMESPACED, KUBE, GET, &[ProblemCode::RateLimited]]),
            }],
        ),
        (
            "/api/v1/namespaces/{ns}/protection-policies",
            vec![Op {
                method: "get",
                operation_id: "listProtectionPolicies",
                summary: "Protection health: the newest point that can actually be recovered from, how availability was decided, the objective, the failed and missed runs, each schedule's OWN readiness beside protection health, and the alert ledger with its delivery state. No sink URL, no routing key and no Secret name: each route publishes its name and which channels it has as booleans.",
                parameters: list_params(),
                request: None,
                success: vec![("200", "One page of protection policies.", "ProtectionPolicyList")],
                problems: all_codes(&[COMMON, NAMESPACED, KUBE, LIST]),
            }],
        ),
        (
            "/api/v1/namespaces/{ns}/protection-policies/{name}",
            vec![Op {
                method: "get",
                operation_id: "getProtectionPolicy",
                summary: "One protection policy. `health` absent means nothing has been evaluated, which is not Healthy.",
                parameters: vec![ns(), name()],
                request: None,
                success: vec![("200", "The policy.", "ProtectionPolicyResponse")],
                problems: all_codes(&[COMMON, NAMESPACED, KUBE, GET]),
            }],
        ),
        (
            "/api/v1/namespaces/{ns}/rehearsal-schedules",
            vec![Op {
                method: "get",
                operation_id: "listRehearsalSchedules",
                summary: "Recurring recovery rehearsals: the last pass, the last failure and the last SKIP with its reason, plus the leftover topics that block the next slot. The signed standing authorization is named, never carried.",
                parameters: list_params(),
                request: None,
                success: vec![("200", "One page of rehearsal schedules.", "RehearsalScheduleList")],
                problems: all_codes(&[COMMON, NAMESPACED, KUBE, LIST]),
            }],
        ),
        (
            "/api/v1/namespaces/{ns}/rehearsal-schedules/{name}",
            vec![Op {
                method: "get",
                operation_id: "getRehearsalSchedule",
                summary: "One rehearsal schedule.",
                parameters: vec![ns(), name()],
                request: None,
                success: vec![("200", "The schedule.", "RehearsalScheduleResponse")],
                problems: all_codes(&[COMMON, NAMESPACED, KUBE, GET]),
            }],
        ),
        (
            "/api/v1/namespaces/{ns}/catalogs",
            vec![
                Op {
                    method: "get",
                    operation_id: "listCatalogs",
                    summary: "Recovery catalogs: the ten verdict counts, the signer list, whether the Kubernetes view is a WINDOW over a larger archive, and when that window ages out with its sync Job.",
                    parameters: list_params(),
                    request: None,
                    success: vec![("200", "One page of catalogs.", "CatalogList")],
                    problems: all_codes(&[COMMON, NAMESPACED, KUBE, LIST]),
                },
                Op {
                    method: "post",
                    operation_id: "connectArchive",
                    summary: "Connect an existing archive (PLAT-15.2): create a RecoveryCatalog under the name in the body, because every protection, rehearsal and retention policy references it by that name. The controller owns the object; this route creates it and nothing else. Repeating the request with the same Idempotency-Key returns the same object.",
                    parameters: vec![ns(), idempotency_key(), origin()],
                    request: Some("ConnectArchiveRequest"),
                    success: vec![
                        ("201", "Created.", "CatalogResponse"),
                        ("200", "Replayed an identical earlier request.", "CatalogResponse"),
                    ],
                    problems: all_codes(&[COMMON, NAMESPACED, KUBE, UNSAFE, CREATE]),
                },
            ],
        ),
        (
            "/api/v1/namespaces/{ns}/catalogs/{name}",
            vec![Op {
                method: "get",
                operation_id: "getCatalog",
                summary: "One catalog.",
                parameters: vec![ns(), name()],
                request: None,
                success: vec![("200", "The catalog.", "CatalogResponse")],
                problems: all_codes(&[COMMON, NAMESPACED, KUBE, GET]),
            }],
        ),
        (
            "/api/v1/namespaces/{ns}/catalogs/{name}/points",
            vec![Op {
                method: "get",
                operation_id: "listCatalogPoints",
                summary: "One page of the materialised point view, with availability and verification as SEPARATE columns and the controller's own `selectable` conjunction beside them. Pages are read by the names the catalog's status records, at most eight per request, and each one is refused unless it is immutable and its bytes match the digest the status recorded. The cursor is bound to the view generation: a view replaced under a paging client is cursor_invalid with 'restart the list', never a silently different page. An empty list with viewExpired true means the window aged out, not that the archive is empty.",
                parameters: vec![
                    ns(),
                    name(),
                    param("limit", "query", "Page size, 1 to 200. Default 50.", json!({ "type": "integer", "minimum": 1, "maximum": 200, "default": 50 }), false),
                    param("cursor", "query", "The opaque nextCursor of the previous page.", json!({ "type": "string" }), false),
                    param("selectable", "query", "true returns only points an ordinary restore may select (Available and verified).", json!({ "type": "string", "enum": ["true", "false"] }), false),
                ],
                request: None,
                success: vec![("200", "One page of recovery points.", "PointPageResponse")],
                problems: all_codes(&[COMMON, NAMESPACED, KUBE, LIST, RESULT_PAGE]),
            }],
        ),
        (
            "/api/v1/namespaces/{ns}/catalogs/{name}/signers",
            vec![Op {
                method: "get",
                operation_id: "listCatalogSigners",
                summary: "The untrusted-signer panel: each key id that signed points in this archive, how many, and whether the bound TrustPolicy accepts it — with the out-of-band fingerprint command and NO route that would trust a key. Absent `trusted` means the catalog could not tell, which is not false and is certainly not true.",
                parameters: vec![ns(), name()],
                request: None,
                success: vec![("200", "The signers.", "SignerPageResponse")],
                problems: all_codes(&[COMMON, NAMESPACED, KUBE, GET]),
            }],
        ),
        (
            "/api/v1/namespaces/{ns}/retention-policies",
            vec![Op {
                method: "get",
                operation_id: "listRetentionPolicies",
                summary: "Retention: what the last evaluation would remove, what is ACTUALLY enforcing it (RecommendationOnly, LogweirWorker or ExternalLifecycleDeclared), which guarantees are Logweir-enforced, provider-declared-unverified or not enforced at all, where the approved-plan gate stands, and whether three consecutive failed runs have set EnforcementDegraded. The delete-capable credential is published as a boolean, never as a Secret name.",
                parameters: list_params(),
                request: None,
                success: vec![("200", "One page of retention policies.", "RetentionPolicyList")],
                problems: all_codes(&[COMMON, NAMESPACED, KUBE, LIST]),
            }],
        ),
        (
            "/api/v1/namespaces/{ns}/retention-policies/{name}",
            vec![Op {
                method: "get",
                operation_id: "getRetentionPolicy",
                summary: "One retention policy, with the plan preview its last evaluation produced. Nothing in `lastEvaluation` was deleted.",
                parameters: vec![ns(), name()],
                request: None,
                success: vec![("200", "The policy.", "RetentionPolicyResponse")],
                problems: all_codes(&[COMMON, NAMESPACED, KUBE, GET]),
            }],
        ),
        (
            "/api/v1/trust-policies",
            vec![Op {
                method: "get",
                operation_id: "listTrustPolicies",
                summary: "The installation's trust policies: which keys are accepted, for what usage, and how fresh that verdict is. CLUSTER-SCOPED, so it has no namespace and requires the administrator role in at least one bound namespace. A key whose evaluation is not fresh — no status, a status from an older generation, or an evaluatedAt older than 15 minutes by THIS server's clock — is published with effectiveState 'unknown' and no usability verdict: unknown is not valid. No public key bytes and no write route.",
                parameters: vec![
                    param("limit", "query", "Page size, 1 to 200. Default 50.", json!({ "type": "integer", "minimum": 1, "maximum": 200, "default": 50 }), false),
                    param("cursor", "query", "The opaque nextCursor of the previous page.", json!({ "type": "string" }), false),
                    param("labelSelector", "query", "Equality-only label selector.", json!({ "type": "string" }), false),
                ],
                request: None,
                success: vec![("200", "One page of trust policies.", "TrustPolicyList")],
                problems: all_codes(&[COMMON, KUBE, LIST, &[ProblemCode::Forbidden]]),
            }],
        ),
        (
            "/api/v1/trust-policies/{name}",
            vec![Op {
                method: "get",
                operation_id: "getTrustPolicy",
                summary: "One trust policy.",
                parameters: vec![name()],
                request: None,
                success: vec![("200", "The policy.", "TrustPolicyResponse")],
                problems: all_codes(&[COMMON, KUBE, GET, &[ProblemCode::Forbidden]]),
            }],
        ),
    ];

    let mut out = Map::new();
    for (path, ops) in table {
        let mut item = Map::new();
        for op in &ops {
            item.insert(op.method.to_string(), operation(op));
        }
        out.insert(path.to_string(), Value::Object(item));
    }
    Value::Object(out)
}

/// The pretty-printed document, newline-terminated.
#[must_use]
pub fn openapi_document() -> String {
    let settings = SchemaSettings::openapi3();
    let mut generator = settings.into_generator();
    // Registering a type adds it and everything it names to the definitions.
    let _ = generator.subschema_for::<Problem>();
    let _ = generator.subschema_for::<c::HealthStatus>();
    let _ = generator.subschema_for::<c::SessionResponse>();
    let _ = generator.subschema_for::<c::NamespaceListResponse>();
    let _ = generator.subschema_for::<c::CreateConnectionRequest>();
    let _ = generator.subschema_for::<c::ConnectionList>();
    let _ = generator.subschema_for::<c::ConnectionResponse>();
    let _ = generator.subschema_for::<c::CreateScheduleRequest>();
    let _ = generator.subschema_for::<c::SetSuspensionRequest>();
    let _ = generator.subschema_for::<c::UpdateSchedulePolicyRequest>();
    let _ = generator.subschema_for::<c::CadencePreviewResponse>();
    let _ = generator.subschema_for::<c::ScheduleList>();
    let _ = generator.subschema_for::<c::ScheduleResponse>();
    let _ = generator.subschema_for::<c::BackupList>();
    let _ = generator.subschema_for::<c::BackupResponse>();
    let _ = generator.subschema_for::<c::CreateBackupRequest>();
    let _ = generator.subschema_for::<c::ManualBackupResponse>();
    let _ = generator.subschema_for::<c::CreateRestoreRequest>();
    let _ = generator.subschema_for::<c::RestoreList>();
    let _ = generator.subschema_for::<c::RestoreResponse>();
    let _ = generator.subschema_for::<c::ApprovalList>();
    let _ = generator.subschema_for::<c::ApprovalResponse>();
    let _ = generator.subschema_for::<c::ApprovalPacketResponse>();
    // BOTH SHAPES STAY PUBLISHED, AND THAT IS NOT AN OVERSIGHT.
    // `OperationViewResponse` is what the route returns and is a strict
    // SUPERSET of `OperationResponse`: D3 §2.5's keys sit beside PLAT-17.1's
    // frozen sixteen, which keep their spellings and their types.
    // `OperationResponse` — and through it `Operation` — is therefore still an
    // accurate description of what a PLAT-17.1 client decodes, and
    // `ui/contract.js`'s `OPERATION` shape is checked against it. Removing it
    // would make a MAJOR change out of a MINOR one: a client written against
    // the frozen shape keeps working, and the document should say so.
    let _ = generator.subschema_for::<c::OperationResponse>();
    let _ = generator.subschema_for::<crate::routes::operations::OperationViewResponse>();
    let _ = generator.subschema_for::<crate::routes::protection::ProtectionPolicyList>();
    let _ = generator.subschema_for::<crate::routes::protection::ProtectionPolicyResponse>();
    let _ = generator.subschema_for::<crate::routes::rehearsals::RehearsalScheduleList>();
    let _ = generator.subschema_for::<crate::routes::rehearsals::RehearsalScheduleResponse>();
    let _ = generator.subschema_for::<crate::routes::catalogs::ConnectArchiveRequest>();
    let _ = generator.subschema_for::<crate::routes::catalogs::CatalogList>();
    let _ = generator.subschema_for::<crate::routes::catalogs::CatalogResponse>();
    let _ = generator.subschema_for::<crate::routes::catalogs::PointPageResponse>();
    let _ = generator.subschema_for::<crate::routes::catalogs::SignerPageResponse>();
    let _ = generator.subschema_for::<crate::routes::retention::RetentionPolicyList>();
    let _ = generator.subschema_for::<crate::routes::retention::RetentionPolicyResponse>();
    let _ = generator.subschema_for::<crate::routes::trust::TrustPolicyList>();
    let _ = generator.subschema_for::<crate::routes::trust::TrustPolicyResponse>();
    let _ = generator.subschema_for::<c::CreateDestinationRequest>();
    let _ = generator.subschema_for::<c::UpdateDestinationAccessRequest>();
    let _ = generator.subschema_for::<c::DestinationFromLegacyRequest>();
    let _ = generator.subschema_for::<c::TestDestinationRequest>();
    let _ = generator.subschema_for::<c::DestinationList>();
    let _ = generator.subschema_for::<c::DestinationResponse>();
    let _ = generator.subschema_for::<c::DestinationUsageResponse>();
    let _ = generator.subschema_for::<c::CreateTopicDiscoveryRequest>();
    let _ = generator.subschema_for::<c::TopicDiscoveryList>();
    let _ = generator.subschema_for::<c::TopicDiscoveryResponse>();
    let _ = generator.subschema_for::<c::TopicPageResponse>();
    let _ = generator.subschema_for::<c::DiscoveryLatestResponse>();
    let _ = generator.subschema_for::<c::CancelResponse>();
    let _ = generator.subschema_for::<c::CreatePreflightRequest>();
    let _ = generator.subschema_for::<c::PreflightResponse>();
    let _ = generator.subschema_for::<c::DetailPageResponse>();
    let _ = generator.subschema_for::<c::CheckOperationResponse>();
    let definitions = generator.take_definitions();
    let schemas: Map<String, Value> = definitions
        .into_iter()
        .map(|(k, v)| (k, serde_json::to_value(v).expect("a schema serialises")))
        .collect();

    let document = json!({
        "openapi": "3.0.3",
        "info": {
            "title": "Logweir product API",
            "version": DOCUMENT_VERSION,
            "description": "The bounded shared-console product API (PLAT-17.1). Not a Kubernetes proxy: no generic resource path, no Secret, Pod, log, exec or Job access, no delete, and no arbitrary patch. Every error is application/problem+json. Unsafe methods require Content-Type: application/json and an Origin equal to the configured public origin. Durable creates require Idempotency-Key. Capabilities without a route are advertised false in /api/v1/session.",
        },
        "paths": paths(),
        "components": {
            "schemas": Value::Object(schemas),
        },
        "x-logweir-reserved-problem-codes": codes(RESERVED),
    });
    let mut text = serde_json::to_string_pretty(&document).expect("the document serialises");
    text.push('\n');
    text
}
