//! The generated OpenAPI 3.0 document.
//!
//! GENERATED FROM THE DTO TYPES, CHECKED IN, DRIFT-TESTED. The component
//! schemas come from `schemars` over `crate::contract` and `crate::problem`;
//! the path table below names every route `crate::app::router` serves. The
//! checked-in copy is `schemas/logweir-api-v1.openapi.json`, regenerated by
//! `just schema` and compared by `just schema-check` and by
//! `tests/contract.rs::the_checked_in_openapi_document_is_what_the_types_generate`.
//! Every route's possible problem codes are listed under
//! `x-logweir-problem-codes`, and a test asserts each code in
//! [`crate::problem::ProblemCode::ALL`] appears somewhere.

use schemars::gen::SchemaSettings;
use serde_json::{json, Map, Value};

use crate::contract as c;
use crate::problem::{Problem, ProblemCode};

/// The document version. `/api/v1` is not yet a stability promise.
pub const DOCUMENT_VERSION: &str = "1.0.0-alpha.1";

fn schema_ref(name: &str) -> Value {
    json!({ "$ref": format!("#/components/schemas/{name}") })
}

fn codes(list: &[ProblemCode]) -> Value {
    Value::Array(
        list.iter()
            .map(|c| Value::String(c.as_str().to_string()))
            .collect(),
    )
}

/// Problem codes any `/api/v1` route can return.
const COMMON: &[ProblemCode] = &[
    ProblemCode::HeaderNotAllowed,
    ProblemCode::MisdirectedRequest,
    ProblemCode::MethodNotAllowed,
    ProblemCode::InternalError,
    ProblemCode::Unauthenticated,
    ProblemCode::SessionExpired,
];

const NAMESPACED: &[ProblemCode] = &[ProblemCode::NamespaceForbidden, ProblemCode::Forbidden];

const KUBE: &[ProblemCode] = &[
    ProblemCode::RateLimited,
    ProblemCode::KubernetesUnavailable,
    ProblemCode::UpstreamTimeout,
];

const LIST: &[ProblemCode] = &[
    ProblemCode::MalformedRequest,
    ProblemCode::ValidationFailed,
    ProblemCode::CursorInvalid,
    ProblemCode::CursorExpired,
];

const GET: &[ProblemCode] = &[ProblemCode::MalformedRequest, ProblemCode::NotFound];

const UNSAFE: &[ProblemCode] = &[
    ProblemCode::OriginMismatch,
    ProblemCode::UnsupportedMediaType,
    ProblemCode::PayloadTooLarge,
    ProblemCode::MalformedRequest,
    ProblemCode::ValidationFailed,
];

const CREATE: &[ProblemCode] = &[
    ProblemCode::IdempotencyKeyRequired,
    ProblemCode::IdempotencyKeyInvalid,
    ProblemCode::IdempotencyConflict,
    ProblemCode::StateConflict,
];

const COMMAND: &[ProblemCode] = &[
    ProblemCode::IdempotencyKeyInvalid,
    ProblemCode::PreconditionFailed,
    ProblemCode::NotFound,
];

/// Problem codes reserved for later stages, with no producing route yet.
const RESERVED: &[ProblemCode] = &[ProblemCode::ApprovalRequired, ProblemCode::PolicyMismatch];

fn all_codes(groups: &[&[ProblemCode]]) -> Vec<ProblemCode> {
    let mut out: Vec<ProblemCode> = Vec::new();
    for group in groups {
        for code in *group {
            if !out.contains(code) {
                out.push(*code);
            }
        }
    }
    out.sort_by_key(|c| c.as_str());
    out
}

struct Op<'a> {
    method: &'static str,
    operation_id: &'a str,
    summary: &'a str,
    parameters: Vec<Value>,
    request: Option<&'a str>,
    success: Vec<(&'a str, &'a str, &'a str)>,
    problems: Vec<ProblemCode>,
}

fn param(name: &str, location: &str, description: &str, schema: Value, required: bool) -> Value {
    json!({
        "name": name,
        "in": location,
        "required": required,
        "description": description,
        "schema": schema,
    })
}

fn ns() -> Value {
    param(
        "ns",
        "path",
        "An explicitly granted namespace. An ungranted namespace is namespace_forbidden whether or not it exists.",
        json!({ "type": "string" }),
        true,
    )
}

fn name() -> Value {
    param(
        "name",
        "path",
        "The object name.",
        json!({ "type": "string" }),
        true,
    )
}

fn list_params() -> Vec<Value> {
    vec![
        ns(),
        param(
            "limit",
            "query",
            "Page size, 1 to 200. Default 50.",
            json!({ "type": "integer", "minimum": 1, "maximum": 200, "default": 50 }),
            false,
        ),
        param(
            "cursor",
            "query",
            "The opaque nextCursor of the previous page. Bound to actor, route, namespace and filters; expires after 15 minutes.",
            json!({ "type": "string" }),
            false,
        ),
        param(
            "labelSelector",
            "query",
            "Equality-only label selector, key=value terms separated by commas.",
            json!({ "type": "string" }),
            false,
        ),
    ]
}

fn idempotency_key() -> Value {
    param(
        "Idempotency-Key",
        "header",
        "8 to 128 visible ASCII characters. The object name is derived from (actor, namespace, route, key); a replay of the same request returns 200 with the same object, a different request with the same key is idempotency_conflict.",
        json!({ "type": "string", "minLength": 8, "maxLength": 128 }),
        true,
    )
}

fn origin() -> Value {
    param(
        "Origin",
        "header",
        "Must equal the configured public origin exactly.",
        json!({ "type": "string" }),
        true,
    )
}

fn operation(op: &Op<'_>) -> Value {
    let mut responses = Map::new();
    for (status, description, schema) in &op.success {
        // An empty schema name means a response with NO body: a 204, or a 303
        // whose only payload is `Location` and `Set-Cookie`. Emitting
        // `$ref: #/components/schemas/` for those would be an invalid document.
        let response = if schema.is_empty() {
            json!({ "description": description })
        } else {
            json!({
                "description": description,
                "content": { "application/json": { "schema": schema_ref(schema) } }
            })
        };
        responses.insert((*status).to_string(), response);
    }
    responses.insert(
        "default".to_string(),
        json!({
            "description": "An application/problem+json error; the possible codes are listed in x-logweir-problem-codes.",
            "content": { "application/problem+json": { "schema": schema_ref("Problem") } }
        }),
    );
    let mut out = Map::new();
    out.insert("operationId".into(), json!(op.operation_id));
    out.insert("summary".into(), json!(op.summary));
    if !op.parameters.is_empty() {
        out.insert("parameters".into(), Value::Array(op.parameters.clone()));
    }
    if let Some(request) = op.request {
        out.insert(
            "requestBody".into(),
            json!({
                "required": true,
                "content": { "application/json": { "schema": schema_ref(request) } }
            }),
        );
    }
    out.insert("responses".into(), Value::Object(responses));
    out.insert("x-logweir-problem-codes".into(), codes(&op.problems));
    Value::Object(out)
}

fn paths() -> Value {
    let list = |id: &'static str, summary: &'static str, schema: &'static str| Op {
        method: "get",
        operation_id: id,
        summary,
        parameters: list_params(),
        request: None,
        success: vec![("200", "One page.", schema)],
        problems: all_codes(&[COMMON, NAMESPACED, KUBE, LIST]),
    };
    let get_one = |id: &'static str, summary: &'static str, schema: &'static str| Op {
        method: "get",
        operation_id: id,
        summary,
        parameters: vec![ns(), name()],
        request: None,
        success: vec![("200", "The object.", schema)],
        problems: all_codes(&[COMMON, NAMESPACED, KUBE, GET]),
    };
    let create =
        |id: &'static str, summary: &'static str, request: &'static str, schema: &'static str| Op {
            method: "post",
            operation_id: id,
            summary,
            parameters: vec![ns(), idempotency_key(), origin()],
            request: Some(request),
            success: vec![
                ("201", "Created.", schema),
                (
                    "200",
                    "Replayed an identical earlier request; the same object.",
                    schema,
                ),
            ],
            problems: all_codes(&[COMMON, NAMESPACED, KUBE, UNSAFE, CREATE]),
        };

    let table: Vec<(&str, Vec<Op<'_>>)> = vec![
        (
            "/healthz",
            vec![Op {
                method: "get",
                operation_id: "getHealthz",
                summary: "Process liveness.",
                parameters: vec![],
                request: None,
                success: vec![("200", "Alive.", "HealthStatus")],
                problems: all_codes(&[&[ProblemCode::HeaderNotAllowed, ProblemCode::MisdirectedRequest]]),
            }],
        ),
        (
            "/readyz",
            vec![Op {
                method: "get",
                operation_id: "getReadyz",
                summary: "Readiness: configuration valid and Kubernetes reachable. No detail is returned.",
                parameters: vec![],
                request: None,
                success: vec![("200", "Ready.", "HealthStatus")],
                problems: all_codes(&[&[
                    ProblemCode::HeaderNotAllowed,
                    ProblemCode::MisdirectedRequest,
                    ProblemCode::KubernetesUnavailable,
                ]]),
            }],
        ),
        (
            "/api/v1/session",
            vec![Op {
                method: "get",
                operation_id: "getSession",
                summary: "The actor, its roles and explicit namespace grants, the synchronizer CSRF token and the capability flags. In shared mode the CSRF token must be sent in X-CSRF-Token on every unsafe method.",
                parameters: vec![],
                request: None,
                success: vec![("200", "The session.", "SessionResponse")],
                problems: all_codes(&[COMMON]),
            }],
        ),
        (
            "/api/v1/session/logout",
            vec![Op {
                method: "post",
                operation_id: "logout",
                summary: "Clear the session cookie. Shared mode only; it is an unsafe method, so it requires the exact Origin, application/json and the synchronizer token like every other mutation.",
                parameters: vec![origin()],
                request: None,
                success: vec![("204", "The session cookie is cleared.", "")],
                problems: all_codes(&[COMMON, &[ProblemCode::OriginMismatch, ProblemCode::UnsupportedMediaType, ProblemCode::NotFound]]),
            }],
        ),
        (
            "/auth/login",
            vec![Op {
                method: "get",
                operation_id: "authLogin",
                summary: "Begin an OpenID Connect Authorization Code + PKCE S256 sign-in. Shared mode only; answers 303 to the provider's authorization endpoint and sets the short-lived __Host-logweir_login cookie holding state, nonce and the PKCE verifier.",
                parameters: vec![param(
                    "next",
                    "query",
                    "Where to land after signing in. Only a path under /ui/ on this origin; anything else is ignored.",
                    json!({ "type": "string" }),
                    false,
                )],
                request: None,
                success: vec![("303", "Redirect to the identity provider.", "")],
                problems: all_codes(&[&[
                    ProblemCode::HeaderNotAllowed,
                    ProblemCode::MisdirectedRequest,
                    ProblemCode::NotFound,
                    ProblemCode::RateLimited,
                    ProblemCode::KubernetesUnavailable,
                ]]),
            }],
        ),
        (
            "/auth/callback",
            vec![Op {
                method: "get",
                operation_id: "authCallback",
                summary: "Finish a sign-in. Shared mode only; validates state, exchanges the code with PKCE, validates the ID token (exact issuer, audience, allowed algorithm, JWKS signature, exp, iat, nonce) and sets __Host-logweir_session. The browser never receives a provider token.",
                parameters: vec![
                    param("code", "query", "The authorization code.", json!({ "type": "string" }), false),
                    param("state", "query", "The state this service issued.", json!({ "type": "string" }), false),
                ],
                request: None,
                success: vec![("303", "Redirect to the console.", "")],
                problems: all_codes(&[&[
                    ProblemCode::HeaderNotAllowed,
                    ProblemCode::MisdirectedRequest,
                    ProblemCode::NotFound,
                    ProblemCode::RateLimited,
                    ProblemCode::Unauthenticated,
                ]]),
            }],
        ),
        (
            "/api/v1/namespaces",
            vec![Op {
                method: "get",
                operation_id: "listNamespaces",
                summary: "The configured namespace grants. Core Namespace objects are never listed.",
                parameters: vec![],
                request: None,
                success: vec![("200", "The grants.", "NamespaceListResponse")],
                problems: all_codes(&[COMMON]),
            }],
        ),
        (
            "/api/v1/namespaces/{ns}/connections",
            vec![
                list("listConnections", "KafkaCluster projections. Secret reference names only.", "ConnectionList"),
                create(
                    "createConnection",
                    "Create a KafkaCluster that references an existing credential Secret by name.",
                    "CreateConnectionRequest",
                    "ConnectionResponse",
                ),
            ],
        ),
        (
            "/api/v1/namespaces/{ns}/connections/{name}",
            vec![get_one("getConnection", "One KafkaCluster projection.", "ConnectionResponse")],
        ),
        (
            "/api/v1/namespaces/{ns}/schedules",
            vec![
                list("listSchedules", "BackupSchedule projections.", "ScheduleList"),
                create("createSchedule", "Create a BackupSchedule.", "CreateScheduleRequest", "ScheduleResponse"),
            ],
        ),
        (
            "/api/v1/namespaces/{ns}/schedules/{name}",
            vec![get_one("getSchedule", "One BackupSchedule projection.", "ScheduleResponse")],
        ),
        (
            "/api/v1/namespaces/{ns}/schedules/{name}:set-suspension",
            vec![Op {
                method: "post",
                operation_id: "setScheduleSuspension",
                summary: "Set spec.suspend, the schedule's one mutable field, if expectedResourceVersion is current. Idempotency-Key is refused.",
                parameters: vec![ns(), name(), origin()],
                request: Some("SetSuspensionRequest"),
                success: vec![("200", "The updated schedule.", "ScheduleResponse")],
                problems: all_codes(&[COMMON, NAMESPACED, KUBE, UNSAFE, COMMAND]),
            }],
        ),
        (
            "/api/v1/namespaces/{ns}/backups",
            vec![list("listBackups", "Backup projections with a status summary.", "BackupList")],
        ),
        (
            "/api/v1/namespaces/{ns}/backups/{name}",
            vec![get_one("getBackup", "One Backup projection.", "BackupResponse")],
        ),
        (
            "/api/v1/namespaces/{ns}/restores",
            vec![
                list("listRestores", "Restore projections with a status summary; planBytes omitted.", "RestoreList"),
                create(
                    "createRestore",
                    "Create a Restore. planBytes is opaque, checked against planHash and stored unchanged.",
                    "CreateRestoreRequest",
                    "RestoreResponse",
                ),
            ],
        ),
        (
            "/api/v1/namespaces/{ns}/restores/{name}",
            vec![get_one("getRestore", "One Restore projection, planBytes included.", "RestoreResponse")],
        ),
        (
            "/api/v1/namespaces/{ns}/approvals",
            vec![list("listApprovals", "Approval metadata; no documents.", "ApprovalList")],
        ),
        (
            "/api/v1/namespaces/{ns}/approvals/{name}",
            vec![get_one("getApproval", "One Approval's metadata; no documents.", "ApprovalResponse")],
        ),
        (
            "/api/v1/namespaces/{ns}/approvals/{name}/packet",
            vec![get_one(
                "getApprovalPacket",
                "The approval and sidecar documents, verbatim.",
                "ApprovalPacketResponse",
            )],
        ),
        (
            "/api/v1/namespaces/{ns}/operations/{kind}/{name}",
            vec![Op {
                method: "get",
                operation_id: "getOperation",
                summary: "The normalized status of one Backup or Restore. Result and evidence verification are separate; NotAttempted is never verified success.",
                parameters: vec![
                    ns(),
                    param(
                        "kind",
                        "path",
                        "backup or restore.",
                        json!({ "type": "string", "enum": ["backup", "restore"] }),
                        true,
                    ),
                    name(),
                ],
                request: None,
                success: vec![("200", "The operation.", "OperationResponse")],
                problems: all_codes(&[COMMON, NAMESPACED, KUBE, GET]),
            }],
        ),
    ];

    let mut out = Map::new();
    for (path, ops) in table {
        let mut item = Map::new();
        for op in &ops {
            item.insert(op.method.to_string(), operation(op));
        }
        out.insert(path.to_string(), Value::Object(item));
    }
    Value::Object(out)
}

/// The pretty-printed document, newline-terminated.
#[must_use]
pub fn openapi_document() -> String {
    let settings = SchemaSettings::openapi3();
    let mut generator = settings.into_generator();
    // Registering a type adds it and everything it names to the definitions.
    let _ = generator.subschema_for::<Problem>();
    let _ = generator.subschema_for::<c::HealthStatus>();
    let _ = generator.subschema_for::<c::SessionResponse>();
    let _ = generator.subschema_for::<c::NamespaceListResponse>();
    let _ = generator.subschema_for::<c::CreateConnectionRequest>();
    let _ = generator.subschema_for::<c::ConnectionList>();
    let _ = generator.subschema_for::<c::ConnectionResponse>();
    let _ = generator.subschema_for::<c::CreateScheduleRequest>();
    let _ = generator.subschema_for::<c::SetSuspensionRequest>();
    let _ = generator.subschema_for::<c::ScheduleList>();
    let _ = generator.subschema_for::<c::ScheduleResponse>();
    let _ = generator.subschema_for::<c::BackupList>();
    let _ = generator.subschema_for::<c::BackupResponse>();
    let _ = generator.subschema_for::<c::CreateRestoreRequest>();
    let _ = generator.subschema_for::<c::RestoreList>();
    let _ = generator.subschema_for::<c::RestoreResponse>();
    let _ = generator.subschema_for::<c::ApprovalList>();
    let _ = generator.subschema_for::<c::ApprovalResponse>();
    let _ = generator.subschema_for::<c::ApprovalPacketResponse>();
    let _ = generator.subschema_for::<c::OperationResponse>();
    let definitions = generator.take_definitions();
    let schemas: Map<String, Value> = definitions
        .into_iter()
        .map(|(k, v)| (k, serde_json::to_value(v).expect("a schema serialises")))
        .collect();

    let document = json!({
        "openapi": "3.0.3",
        "info": {
            "title": "Logweir product API",
            "version": DOCUMENT_VERSION,
            "description": "The bounded shared-console product API (PLAT-17.1). Not a Kubernetes proxy: no generic resource path, no Secret, Pod, log, exec or Job access, no delete, and no arbitrary patch. Every error is application/problem+json. Unsafe methods require Content-Type: application/json and an Origin equal to the configured public origin. Durable creates require Idempotency-Key. Capabilities without a route are advertised false in /api/v1/session.",
        },
        "paths": paths(),
        "components": {
            "schemas": Value::Object(schemas),
        },
        "x-logweir-reserved-problem-codes": codes(RESERVED),
    });
    let mut text = serde_json::to_string_pretty(&document).expect("the document serialises");
    text.push('\n');
    text
}
