// emit-plan.js -- the golden's emitter.
//
// Writes `renderPlanBytes(<ui/tests/fixtures/plan-fields.json>)` to stdout,
// byte for byte, with nothing added and no trailing newline of its own. That
// is what lets `scripts/check-ui-behaviour.sh` run
//
//     node ui/tests/emit-plan.js > "$tmp" && diff -u ui/tests/fixtures/plan.golden.yaml "$tmp"
//
// with the exit status read directly, so a regenerated golden and the
// committed one cannot drift.
//
// REGENERATING THE GOLDEN is the same command with the redirect pointed at the
// fixture:
//
//     node ui/tests/emit-plan.js > ui/tests/fixtures/plan.golden.yaml
//
// That is a deliberate two-step: regenerating it does not make it correct.
// `render_plan_bytes_emits_a_document_the_runner_parses` arm 1 deserialises the
// regenerated bytes into `logweir_core::spec::RestoreSpec` from Rust, so a
// golden regenerated from an emitter that invented a shape fails the Rust half
// even though the two JavaScript halves now agree with each other.
//
// It reaches no network and writes no file: one read, one render, one write to
// stdout.

import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";

import { renderPlanBytes } from "../plan.js";

const fields = JSON.parse(
  readFileSync(fileURLToPath(new URL("./fixtures/plan-fields.json", import.meta.url)), "utf8"),
);

process.stdout.write(renderPlanBytes(fields));
